### ISSUE TITLE
problems with the latest version of outwatch

### ISSUE THREAD

**Issue by elyphas** [clovellytech/outwatch-router#4]
I have troubles trying to compile outwatch latest version with outwatch-router, seems there are conflict between two different version of snabbdom.

**Comment by zakpatterson** [comment]
I can see how that would happen with the jitpack repository dependency maybe. Can you have a go at a PR to update? https://github.com/clovellytech/outwatch-router/blob/master/build.sbt#L84

**Comment by elyphas** [comment]
I tried, I have troubles with permissions

**Comment by zakpatterson** [comment]
I see. You must fork this repository first and push your changes to your fork. I would read this article: https://help.github.com/en/articles/fork-a-repo

**Comment by elyphas** [comment]
Thank you, i will check it out

**Comment by zakpatterson** [comment]
Hi @elyphas I updated and merged your #5 PR, I think it should work now. Please try out v0.0.7 when you can. Feel free to reopen this issue if you're still having this problem. Thanks!

**Comment by elyphas** [comment]
Ok thank you
